function exclusions = get_r1_dynamic_training_exclusions()
%GET_R1_DYNAMIC_TRAINING_EXCLUSIONS Accepted topology-scenario exclusions for R1.
%
% These exclusions freeze the final dynamic-surrogate training scope after
% physical-power reconstruction. The retained rule is intentionally narrow:
% only the two previously identified isolated low-efficiency anomalies are
% removed from the accepted training and Fig. 3a envelope datasets.

exclusions = table( ...
    [357; 346], ...
    [2; 3], ...
    ["M2"; "M3"], ...
    [0.296833333333333; 0.280989583333333], ...
    ["isolated low-efficiency anomaly in the 0.25 p.u. mean-power bin"; ...
     "isolated low-efficiency anomaly in the 0.25 p.u. mean-power bin"], ...
    'VariableNames', { ...
    'scenario_id', 'topology_id', 'topology_label', 'mean_power_pu', 'reason'});
end
