function outputs = run_stack_sft_si()
% Generate stack/SFT model data for the R1 Supplementary Information.

cfg = pipeline_config();
addpath(cfg.stack_model_dir);
addpath(fileparts(mfilename('fullpath')));

outDir = fullfile(cfg.output_dir, 'stack_sft');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

caseTable = stack_case_library();
searchRegion = build_stack_sft_search_region( ...
    caseTable, cfg.flow_segmentation_k, cfg.flow_segmentation_pipe_k);
parameterTableS4 = build_stack_sft_table_s4_parameters();

currentFractions = [0.02, 0.05, 0.1:0.1:1];
curveRows = {};
summaryRows = {};

for i = 1:height(searchRegion)
    stackCase = table_row_to_stack_case(caseTable, searchRegion.base_case_id(i));
    curve = evaluate_stack_sft_case( ...
        stackCase, searchRegion.k_seg(i), currentFractions, ...
        cfg.flow_segmentation_area_policy);

    for j = 1:height(curve)
        curveRows(end+1, :) = { ...
            searchRegion.design_id(i), searchRegion.design_label{i}, ...
            searchRegion.stack_size_MW(i), searchRegion.capacity_Nm3h(i), ...
            searchRegion.geometry{i}, searchRegion.k_seg(i), ...
            searchRegion.segment_vector{i}, ...
            cfg.flow_segmentation_area_policy, ...
            curve.current_fraction(j), curve.input_current_A(j), ...
            curve.stack_power_pu(j), ...
            curve.stack_power_MW(j), curve.stack_voltage_V(j), ...
            curve.average_cell_voltage_V(j), ...
            curve.current_efficiency(j), curve.stack_efficiency_LHV(j), ...
            curve.stack_voltage_external_T90_V(j), ...
            curve.average_cell_voltage_external_T90_V(j), ...
            curve.stack_power_external_T90_MW(j), ...
            curve.stack_efficiency_thermoneutral_T90(j), ...
            curve.stack_voltage_external_T60_V(j), ...
            curve.average_cell_voltage_external_T60_V(j), ...
            curve.stack_power_external_T60_MW(j), ...
            curve.stack_efficiency_thermoneutral_T60(j), ...
            curve.H2_mol_s(j), curve.H2_Nm3_h(j), ...
            curve.cell_current_min_A(j), curve.cell_current_max_A(j), ...
            curve.cell_current_min_over_max(j), ...
            curve.cell_current_std_over_mean(j), ...
            curve.absolute_stray_current_ratio(j) ...
            }; %#ok<AGROW>
    end

    rated = curve(end, :);
    summaryRows(end+1, :) = { ...
        searchRegion.design_id(i), searchRegion.design_label{i}, ...
        searchRegion.stack_size_MW(i), searchRegion.capacity_Nm3h(i), ...
        searchRegion.geometry{i}, searchRegion.k_seg(i), ...
        searchRegion.segment_vector{i}, ...
        searchRegion.is_original_case(i), searchRegion.is_pipe_interface(i), ...
        rated.stack_power_MW, rated.stack_voltage_V, ...
        rated.average_cell_voltage_V, rated.current_efficiency, ...
        rated.stack_efficiency_LHV, rated.H2_Nm3_h, ...
        rated.stack_voltage_external_T90_V, ...
        rated.average_cell_voltage_external_T90_V, ...
        rated.stack_power_external_T90_MW, ...
        rated.stack_efficiency_thermoneutral_T90, ...
        rated.stack_voltage_external_T60_V, ...
        rated.average_cell_voltage_external_T60_V, ...
        rated.stack_power_external_T60_MW, ...
        rated.stack_efficiency_thermoneutral_T60, ...
        rated.cell_current_min_over_max, rated.cell_current_std_over_mean, ...
        rated.absolute_stray_current_ratio ...
        }; %#ok<AGROW>
end

curves = cell2table(curveRows, 'VariableNames', { ...
    'design_id', 'design_label', 'stack_size_MW', 'capacity_Nm3h', ...
    'geometry', 'k_seg', 'segment_vector', 'area_policy', ...
    'current_fraction', 'input_current_A', ...
    'stack_power_pu', 'stack_power_MW', ...
    'stack_voltage_V', 'average_cell_voltage_V', ...
    'current_efficiency', 'stack_efficiency_LHV', ...
    'stack_voltage_external_T90_V', 'average_cell_voltage_external_T90_V', ...
    'stack_power_external_T90_MW', 'stack_efficiency_thermoneutral_T90', ...
    'stack_voltage_external_T60_V', 'average_cell_voltage_external_T60_V', ...
    'stack_power_external_T60_MW', 'stack_efficiency_thermoneutral_T60', ...
    'H2_mol_s', 'H2_Nm3_h', ...
    'cell_current_min_A', 'cell_current_max_A', ...
    'cell_current_min_over_max', 'cell_current_std_over_mean', ...
    'absolute_stray_current_ratio' ...
    });
curves = add_curve_relative_gain(curves);

summary = cell2table(summaryRows, 'VariableNames', { ...
    'design_id', 'design_label', 'stack_size_MW', 'capacity_Nm3h', ...
    'geometry', 'k_seg', 'segment_vector', ...
    'is_original_case', 'is_pipe_interface', ...
    'rated_stack_power_MW', 'rated_stack_voltage_V', ...
    'rated_average_cell_voltage_V', 'rated_current_efficiency', ...
    'rated_stack_efficiency_LHV', 'rated_H2_Nm3_h', ...
    'rated_stack_voltage_external_T90_V', ...
    'rated_average_cell_voltage_external_T90_V', ...
    'rated_stack_power_external_T90_MW', ...
    'rated_stack_efficiency_thermoneutral_T90', ...
    'rated_stack_voltage_external_T60_V', ...
    'rated_average_cell_voltage_external_T60_V', ...
    'rated_stack_power_external_T60_MW', ...
    'rated_stack_efficiency_thermoneutral_T60', ...
    'rated_cell_current_min_over_max', ...
    'rated_cell_current_std_over_mean', ...
    'rated_absolute_stray_current_ratio' ...
    });
summary = add_summary_relative_gain(summary);

pipeCurves = curves(curves.stack_size_MW >= 0 & strcmp(curves.geometry, 'equal_VA') ...
    & (curves.k_seg == 1 | curves.k_seg == cfg.flow_segmentation_pipe_k), :);

policySensitivity = run_area_policy_sensitivity(caseTable, currentFractions(end), ...
    cfg.flow_segmentation_pipe_k);

write_outputs(outDir, caseTable, searchRegion, parameterTableS4, summary, curves, ...
    pipeCurves, policySensitivity);
write_si_note(outDir, cfg, searchRegion, parameterTableS4, summary);

outputs = struct();
outputs.output_dir = outDir;
outputs.case_table = caseTable;
outputs.search_region = searchRegion;
outputs.parameter_table_s4 = parameterTableS4;
outputs.summary = summary;
outputs.curves = curves;
outputs.pipe_curves = pipeCurves;
outputs.policy_sensitivity = policySensitivity;

disp('Stack SFT SI model data generated.');
disp(outDir);
end

function T = add_curve_relative_gain(T)
n = height(T);
deltaEtaI = nan(n, 1);
ratioEtaI = nan(n, 1);
deltaEtaStack = nan(n, 1);
ratioEtaStack = nan(n, 1);
deltaMinMax = nan(n, 1);
isBaselineProductive = false(n, 1);
isCaseProductive = T.current_efficiency > 0;

for i = 1:n
    idx = T.stack_size_MW == T.stack_size_MW(i) ...
        & strcmp(T.geometry, T.geometry{i}) ...
        & abs(T.current_fraction - T.current_fraction(i)) < 1e-12 ...
        & T.k_seg == 1;
    base = T(find(idx, 1), :);
    if ~isempty(base)
        isBaselineProductive(i) = base.current_efficiency > 0;
        deltaEtaI(i) = T.current_efficiency(i) - base.current_efficiency;
        deltaEtaStack(i) = T.stack_efficiency_LHV(i) - base.stack_efficiency_LHV;
        deltaMinMax(i) = T.cell_current_min_over_max(i) - base.cell_current_min_over_max;
        if base.current_efficiency > 0
            ratioEtaI(i) = T.current_efficiency(i) / base.current_efficiency;
        end
        if base.stack_efficiency_LHV > 0
            ratioEtaStack(i) = T.stack_efficiency_LHV(i) / base.stack_efficiency_LHV;
        end
    end
end

T.delta_current_efficiency_vs_k1 = deltaEtaI;
T.ratio_current_efficiency_vs_k1 = ratioEtaI;
T.delta_stack_efficiency_LHV_vs_k1 = deltaEtaStack;
T.ratio_stack_efficiency_LHV_vs_k1 = ratioEtaStack;
T.delta_cell_current_min_over_max_vs_k1 = deltaMinMax;
T.is_case_productive = isCaseProductive;
T.is_baseline_productive = isBaselineProductive;
end

function T = add_summary_relative_gain(T)
n = height(T);
deltaEtaI = nan(n, 1);
ratioEtaI = nan(n, 1);
deltaEtaStack = nan(n, 1);
ratioEtaStack = nan(n, 1);
deltaMinMax = nan(n, 1);

for i = 1:n
    idx = T.stack_size_MW == T.stack_size_MW(i) ...
        & strcmp(T.geometry, T.geometry{i}) ...
        & T.k_seg == 1;
    base = T(find(idx, 1), :);
    if ~isempty(base)
        deltaEtaI(i) = T.rated_current_efficiency(i) - base.rated_current_efficiency;
        deltaEtaStack(i) = T.rated_stack_efficiency_LHV(i) - base.rated_stack_efficiency_LHV;
        deltaMinMax(i) = T.rated_cell_current_min_over_max(i) - base.rated_cell_current_min_over_max;
        if base.rated_current_efficiency > 0
            ratioEtaI(i) = T.rated_current_efficiency(i) / base.rated_current_efficiency;
        end
        if base.rated_stack_efficiency_LHV > 0
            ratioEtaStack(i) = T.rated_stack_efficiency_LHV(i) / base.rated_stack_efficiency_LHV;
        end
    end
end

T.delta_rated_current_efficiency_vs_k1 = deltaEtaI;
T.ratio_rated_current_efficiency_vs_k1 = ratioEtaI;
T.delta_rated_stack_efficiency_LHV_vs_k1 = deltaEtaStack;
T.ratio_rated_stack_efficiency_LHV_vs_k1 = ratioEtaStack;
T.delta_rated_cell_current_min_over_max_vs_k1 = deltaMinMax;
end

function stackCase = table_row_to_stack_case(caseTable, caseId)
row = caseTable(caseTable.case_id == caseId, :);
if height(row) ~= 1
    error('Expected exactly one stack case for case_id=%d.', caseId);
end

stackCase = struct();
stackCase.case_id = row.case_id;
stackCase.stack_size_MW = row.stack_size_MW;
stackCase.capacity_Nm3h = row.capacity_Nm3h;
stackCase.geometry = row.geometry{1};
stackCase.n_cell = row.n_cell;
stackCase.rated_current_A = row.rated_current_A;
stackCase.R0_ohm = row.R0_ohm;
stackCase.U0_V = row.U0_V;
stackCase.cell_area_scale = row.cell_area_scale;
stackCase.channel_area_scale = row.channel_area_scale;
stackCase.manifold_area_scale = row.manifold_area_scale;
stackCase.channel_length_m = row.channel_length_m;
stackCase.channel_area_m2 = row.channel_area_m2;
stackCase.manifold_length_m = row.manifold_length_m;
stackCase.manifold_area_m2 = row.manifold_area_m2;
stackCase.rated_alkali_flow_m3_h = row.rated_alkali_flow_m3_h;
end

function T = run_area_policy_sensitivity(caseTable, currentFraction, pipeK)
policies = {'total_area_conserved', 'branch_area_preserved'};
rows = {};
idx = 0;
equalVA = caseTable(strcmp(caseTable.geometry, 'equal_VA'), :);

for i = 1:height(equalVA)
    stackCase = table_row_to_stack_case(caseTable, equalVA.case_id(i));
    for p = 1:numel(policies)
        idx = idx + 1;
        curve = evaluate_stack_sft_case(stackCase, pipeK, currentFraction, policies{p});
        rows(idx, :) = { ...
            equalVA.stack_size_MW(i), equalVA.capacity_Nm3h(i), ...
            equalVA.geometry{i}, pipeK, policies{p}, ...
            curve.stack_power_MW, curve.stack_voltage_V, ...
            curve.current_efficiency, curve.stack_efficiency_LHV, ...
            curve.stack_efficiency_thermoneutral_T90, ...
            curve.stack_efficiency_thermoneutral_T60, ...
            curve.cell_current_min_over_max, curve.absolute_stray_current_ratio ...
            }; %#ok<AGROW>
    end
end

T = cell2table(rows, 'VariableNames', { ...
    'stack_size_MW', 'capacity_Nm3h', 'geometry', 'k_seg', 'area_policy', ...
    'rated_stack_power_MW', 'rated_stack_voltage_V', ...
    'rated_current_efficiency', 'rated_stack_efficiency_LHV', ...
    'rated_stack_efficiency_thermoneutral_T90', ...
    'rated_stack_efficiency_thermoneutral_T60', ...
    'rated_cell_current_min_over_max', ...
    'rated_absolute_stray_current_ratio' ...
    });
end

function write_outputs(outDir, caseTable, searchRegion, parameterTableS4, summary, curves, pipeCurves, policySensitivity)
writetable(caseTable, fullfile(outDir, 'stack_sft_model_parameters.csv'));
writetable(searchRegion, fullfile(outDir, 'stack_sft_search_region.csv'));
writetable(parameterTableS4, fullfile(outDir, 'stack_sft_table_s4_style_parameters.csv'));
writetable(summary, fullfile(outDir, 'stack_sft_rated_summary.csv'));
writetable(curves, fullfile(outDir, 'stack_sft_efficiency_curves.csv'));
writetable(pipeCurves, fullfile(outDir, 'stack_sft_pipe_interface_curves.csv'));
writetable(curves(:, {'design_id', 'design_label', 'stack_size_MW', 'geometry', ...
    'k_seg', 'current_fraction', 'stack_power_pu', ...
    'is_case_productive', 'is_baseline_productive', ...
    'delta_current_efficiency_vs_k1', 'ratio_current_efficiency_vs_k1', ...
    'delta_stack_efficiency_LHV_vs_k1', 'ratio_stack_efficiency_LHV_vs_k1', ...
    'delta_cell_current_min_over_max_vs_k1'}), ...
    fullfile(outDir, 'stack_sft_relative_gain_curves.csv'));
writetable(policySensitivity, fullfile(outDir, 'stack_sft_area_policy_sensitivity.csv'));

xlsxPath = fullfile(outDir, 'stack_sft_SI_model_data.xlsx');
writetable(caseTable, xlsxPath, 'Sheet', 'model_parameters');
writetable(searchRegion, xlsxPath, 'Sheet', 'search_region');
writetable(parameterTableS4, xlsxPath, 'Sheet', 'table_s4_style_params');
writetable(summary, xlsxPath, 'Sheet', 'rated_summary');
writetable(curves, xlsxPath, 'Sheet', 'efficiency_curves');
writetable(curves(:, {'design_id', 'design_label', 'stack_size_MW', 'geometry', ...
    'k_seg', 'current_fraction', 'stack_power_pu', ...
    'is_case_productive', 'is_baseline_productive', ...
    'delta_current_efficiency_vs_k1', 'ratio_current_efficiency_vs_k1', ...
    'delta_stack_efficiency_LHV_vs_k1', 'ratio_stack_efficiency_LHV_vs_k1', ...
    'delta_cell_current_min_over_max_vs_k1'}), ...
    xlsxPath, 'Sheet', 'relative_gain');
writetable(pipeCurves, xlsxPath, 'Sheet', 'pipe_interfaces');
writetable(policySensitivity, xlsxPath, 'Sheet', 'area_policy_check');
end

function write_si_note(outDir, cfg, searchRegion, parameterTableS4, summary)
notePath = fullfile(outDir, 'stack_sft_SI_method_note.md');
fid = fopen(notePath, 'w');
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, '# Stack-layer SFT model-data note\n\n');
fprintf(fid, 'Purpose: this file records the stack-layer data generated for the R1 SI update.\n\n');
fprintf(fid, 'Default SFT area policy: `%s`.\n\n', cfg.flow_segmentation_area_policy);
fprintf(fid, 'Search-region size: %d stack designs. Original cases: %d. Pipe-interface cases: %d.\n\n', ...
    height(searchRegion), sum(searchRegion.is_original_case), sum(searchRegion.is_pipe_interface));
fprintf(fid, 'Practical SFT scheme propagated to the module layer: 5 MW remains at `k_seg = 1`; 10 MW includes `k_seg = 1, 2`; 20 MW includes `k_seg = 1, 2, 4`.\n\n');
fprintf(fid, 'Table-S4-style parameter rows: %d.\n\n', height(parameterTableS4));

fprintf(fid, '## SI wording draft\n\n');
fprintf(fid, ['For the stack-layer search-region extension, we introduced a flow-path segmentation variable, ', ...
    '`k_seg`, following the segmented flow-path topology concept. The original continuous-flow topology ', ...
    'corresponds to `k_seg = 1`. For `k_seg > 1`, the stack is partitioned into adjacent-cell segments ', ...
    'with segment sizes differing by at most one cell. Each segment retains the original equivalent-circuit ', ...
    'element equations and cell electrochemistry; the flow topology is represented by solving the equivalent ', ...
    'circuit for each local segment and summing the segment voltages and effective electrolysis currents.\n\n']);
fprintf(fid, ['For the equal-segmentation cases used here, the calculation can be written as a representative-segment ', ...
    'calculation followed by a multiplicity aggregation. Let n_seg = N_cell/k_seg and let i_el,c,seg denote ', ...
    'the effective electrolysis current of cell c in the representative segment. The segment effective electrolysis ', ...
    'current is I_el,seg = sum_c i_el,c,seg and the full-stack effective electrolysis current is ', ...
    'I_el,stack = k_seg I_el,seg. The current efficiency is eta_current = I_el,stack/(I_0 N_cell) = ', ...
    'I_el,seg/(I_0 n_seg). The external stack voltage is calculated separately from the semi-empirical ', ...
    'cell-voltage equation U_cell(I_0,T) = U_0 + R_0(T)I_0, with ', ...
    'R_0(T) = (9.4410 - 0.0250T) x 10^-5/(2A_scale). Thus U_stack = N_cell U_cell(I_0,T), ', ...
    'P_stack = I_0 U_stack, and eta_stack = eta_current V_TN/U_cell(I_0,T), where V_TN = 1.48 V is ', ...
    'the thermoneutral voltage. The T = 90 degC and T = 60 degC voltage-efficiency bounds reproduce the ', ...
    'upper and lower stack-efficiency curves in Fig. 2a.\n\n']);
fprintf(fid, ['Unless otherwise stated, the total manifold area is conserved across the flow-path segments as a ', ...
    'conservative modelling assumption. In the ECN input, ', ...
    'the per-segment manifold area is set as S_m,seg = S_m,original * n_seg / N_cell; for equal segmentation this reduces to S_m,original / k_seg. ', ...
    'The rated alkali flow is treated in the same way, while the total stack rating and module-level thermal parameters remain unchanged.\n\n']);
fprintf(fid, ['This treatment deliberately modifies the shared transverse manifold rather than the single-cell longitudinal channels. ', ...
    'The longitudinal channel parameters describe the local flow path inside each cell and are inherited from the parent equal-V/A stack, ', ...
    'because flow-path segmentation does not redesign the cell-level flow field. By contrast, the transverse manifold represents the ', ...
    'shared electrolyte-conduction path connecting many cells; segmentation shortens this shared path and breaks one large current-distribution ', ...
    'profile into several smaller local profiles. Keeping the longitudinal channels unchanged therefore separates the stack-level SFT extension ', ...
    'from an independent channel or flow-field optimisation problem.\n\n']);
fprintf(fid, ['In the paper pipeline, the segmented-flow case updates the current-efficiency term through ', ...
    'the ECN current-distribution calculation, while the voltage-efficiency term is evaluated from the ', ...
    'same semi-empirical external voltage equation as the original Fig. 2a stack-efficiency curves.\n\n']);
fprintf(fid, ['At very low input currents, the ECN may predict non-productive or reverse local electrolysis ', ...
    'currents because shunt paths dominate. These points are retained in the raw curve table, but ', ...
    'relative gain ratios are reported only when the k_seg = 1 baseline has positive current efficiency.\n\n']);

fprintf(fid, '## Rated pipe-interface summary\n\n');
pipe = summary(summary.is_pipe_interface, :);
for i = 1:height(pipe)
    fprintf(fid, '- %s: eta_T90 = %.4f, eta_T60 = %.4f, eta_current = %.4f, min/max current = %.4f.\n', ...
        pipe.design_label{i}, pipe.rated_stack_efficiency_thermoneutral_T90(i), ...
        pipe.rated_stack_efficiency_thermoneutral_T60(i), ...
        pipe.rated_current_efficiency(i), pipe.rated_cell_current_min_over_max(i));
end
end
