function run_plant_milp_dynamic_closed_loop()
%RUN_PLANT_MILP_DYNAMIC_CLOSED_LOOP Run the closed plant pipeline:
%   static P-H2 interface -> MILP dispatch
%   -> dynamic LSBoost interface -> final plant performance.
%
% The output compares the MILP-generated schedule with the original theta
% dispatch family under the same dynamic evaluation interface.

cfg = plant_case_config();
addpath(cfg.flow_src_dir);

for topology_id = cfg.topology_ids
    load_dynamic_eta_model(topology_id, cfg);
end
file_suffix = "";

maps = load_module_ph_map(cfg);
cases = load_plant_power_profiles(cfg);

summary_rows = {};
theta_rows = {};
gain_rows = {};
theta_summary_rows = {};
theta_daily_rows = {};
theta_series = struct();
profile_rows = {};
process_dir = fullfile(cfg.output_dir, 'process_milp_dynamic');
if ~exist(process_dir, 'dir')
    mkdir(process_dir);
end

theta_fit_grid = 0:0.01:1;

for ci = 1:numel(cases)
    case_name = string(cases(ci).name);
    case_cfg = cfg;
    case_cfg.n_modules = cases(ci).n_modules;
    case_cfg.plant_rating_MW = cases(ci).plant_rating_MW;

    P_available = cases(ci).P_available_MW(:);
    P_capped = min(P_available, case_cfg.plant_rating_MW);
    mean_load_raw = mean(P_available) / case_cfg.plant_rating_MW;
    mean_load_capped = mean(P_capped) / case_cfg.plant_rating_MW;
    available_energy_MWh = sum(P_available) * case_cfg.delta_t_hour;
    capped_energy_MWh = sum(P_capped) * case_cfg.delta_t_hour;
    steps_per_day = round(24 / case_cfg.delta_t_hour);
    n_days = numel(P_available) / steps_per_day;

    profile_rows(end + 1, :) = { ...
        case_name, case_cfg.n_modules, case_cfg.plant_rating_MW, ...
        mean_load_raw, mean_load_capped, available_energy_MWh, capped_energy_MWh, ...
        min(P_available), max(P_available), n_days ...
        }; %#ok<SAGROW>

    fprintf('Case %s: %d modules, %.0f MW, mean load %.4f\n', ...
        case_name, case_cfg.n_modules, case_cfg.plant_rating_MW, mean_load_capped);

    for mi = 1:numel(maps)
        ph_map = maps(mi);
        topology_id = ph_map.topology_id;
        topology_label = string(ph_map.topology_label);

        milp = dispatch_milp_static_map(P_available, ph_map, case_cfg);
        milp_dyn = evaluate_dynamic_surrogate_schedule(milp.Pmodule_MW, topology_id, case_cfg);
        milp_curtailment_MWh = sum(max(P_available - milp_dyn.Pused_MW, 0)) * case_cfg.delta_t_hour;
        milp_used_energy_day = sum(milp_dyn.energy_day_module_MWh, 2);
        milp_hydrogen_day = sum(milp_dyn.hydrogen_day_module_t, 2);
        milp_curtailment_day = reshape(max(P_available - milp_dyn.Pused_MW, 0), steps_per_day, [])';
        milp_curtailment_day_MWh = sum(milp_curtailment_day, 2) * case_cfg.delta_t_hour;
        milp_active_day = reshape(sum(milp.Pmodule_MW > 1e-9, 2), steps_per_day, [])';
        milp_active_day_mean = mean(milp_active_day, 2);
        milp_eta_day_mean = mean(milp_dyn.eta_day_module, 2);

        eq_theta = fit_equivalent_theta_series(milp.Pmodule_MW, P_available, case_cfg, theta_fit_grid);
        theta_key = char(matlab.lang.makeValidName(sprintf('%s_%s', case_name, topology_label)));
        theta_series.(theta_key) = eq_theta;
        add_equivalent_theta_summary(eq_theta, case_name, topology_label, topology_id);
        add_equivalent_theta_daily(eq_theta, case_name, topology_label, topology_id);

        summary_rows(end + 1, :) = { ...
            case_name, topology_label, topology_id, ...
            "MILP_static_dispatch_dynamic_eval", NaN, ...
            case_cfg.n_modules, case_cfg.plant_rating_MW, ...
            mean_load_raw, mean_load_capped, ...
            available_energy_MWh, capped_energy_MWh, milp_dyn.energy_MWh, ...
            milp_dyn.hydrogen_t, milp_dyn.efficiency_LHV, ...
            milp_curtailment_MWh, mean(sum(milp.Pmodule_MW > 1e-9, 2)), ...
            mean(eq_theta.equivalent_theta), mean(eq_theta.theta_fit_rmse_MW), ...
            mean(eq_theta.loading_gini) ...
            }; %#ok<SAGROW>

        best_theta = NaN;
        best_theta_dyn = [];
        best_theta_hydrogen = -inf;
        best_theta_curtailment_MWh = NaN;
        best_theta_active = NaN;
        best_theta_schedule = [];
        best_theta_used_energy_day = [];
        best_theta_hydrogen_day = [];
        best_theta_eta_day_mean = [];
        best_theta_curtailment_day_MWh = [];
        best_theta_active_day_mean = [];
        theta_process = struct([]);

        for th = 1:numel(cfg.theta_grid)
            theta = cfg.theta_grid(th);
            Ptheta3 = dispatch_theta_rule(P_available', theta, case_cfg);
            Ptheta = squeeze(Ptheta3(1, :, :));
            if isvector(Ptheta)
                Ptheta = Ptheta(:);
            end
            theta_dyn = evaluate_dynamic_surrogate_schedule(Ptheta, topology_id, case_cfg);
            theta_curtailment_MWh = sum(max(P_available - theta_dyn.Pused_MW, 0)) * case_cfg.delta_t_hour;
            theta_active = mean(sum(Ptheta > 1e-9, 2));
            theta_used_energy_day = sum(theta_dyn.energy_day_module_MWh, 2);
            theta_hydrogen_day = sum(theta_dyn.hydrogen_day_module_t, 2);
            theta_curtailment_day = reshape(max(P_available - theta_dyn.Pused_MW, 0), steps_per_day, [])';
            theta_curtailment_day_MWh = sum(theta_curtailment_day, 2) * case_cfg.delta_t_hour;
            theta_active_day = reshape(sum(Ptheta > 1e-9, 2), steps_per_day, [])';
            theta_active_day_mean = mean(theta_active_day, 2);
            theta_eta_day_mean = mean(theta_dyn.eta_day_module, 2);

            theta_process(th).theta = theta;
            theta_process(th).Pmodule_MW = Ptheta;
            theta_process(th).Pused_MW = theta_dyn.Pused_MW;
            theta_process(th).features = theta_dyn.features;
            theta_process(th).eta_day_module = theta_dyn.eta_day_module;
            theta_process(th).energy_day_module_MWh = theta_dyn.energy_day_module_MWh;
            theta_process(th).hydrogen_day_module_t = theta_dyn.hydrogen_day_module_t;
            theta_process(th).used_energy_day_MWh = theta_used_energy_day;
            theta_process(th).hydrogen_day_t = theta_hydrogen_day;
            theta_process(th).curtailment_day_MWh = theta_curtailment_day_MWh;
            theta_process(th).active_modules_day_mean = theta_active_day_mean;

            theta_rows(end + 1, :) = { ...
                case_name, topology_label, topology_id, theta, ...
                case_cfg.n_modules, case_cfg.plant_rating_MW, ...
                mean_load_raw, mean_load_capped, theta_dyn.energy_MWh, ...
                theta_dyn.hydrogen_t, theta_dyn.efficiency_LHV, ...
                theta_curtailment_MWh, theta_active ...
                }; %#ok<SAGROW>

            if theta_dyn.hydrogen_t > best_theta_hydrogen
                best_theta_hydrogen = theta_dyn.hydrogen_t;
                best_theta = theta;
                best_theta_dyn = theta_dyn;
                best_theta_curtailment_MWh = theta_curtailment_MWh;
                best_theta_active = theta_active;
                best_theta_schedule = Ptheta;
                best_theta_used_energy_day = theta_used_energy_day;
                best_theta_hydrogen_day = theta_hydrogen_day;
                best_theta_eta_day_mean = theta_eta_day_mean;
                best_theta_curtailment_day_MWh = theta_curtailment_day_MWh;
                best_theta_active_day_mean = theta_active_day_mean;
            end
        end

        summary_rows(end + 1, :) = { ...
            case_name, topology_label, topology_id, ...
            "Best_theta_rule_dynamic_eval", best_theta, ...
            case_cfg.n_modules, case_cfg.plant_rating_MW, ...
            mean_load_raw, mean_load_capped, ...
            available_energy_MWh, capped_energy_MWh, best_theta_dyn.energy_MWh, ...
            best_theta_dyn.hydrogen_t, best_theta_dyn.efficiency_LHV, ...
            best_theta_curtailment_MWh, best_theta_active, ...
            best_theta, NaN, NaN ...
            }; %#ok<SAGROW>

        hydrogen_gain_percent = (milp_dyn.hydrogen_t - best_theta_dyn.hydrogen_t) ...
            / max(best_theta_dyn.hydrogen_t, eps) * 100;
        efficiency_gain_percent = (milp_dyn.efficiency_LHV - best_theta_dyn.efficiency_LHV) ...
            / max(best_theta_dyn.efficiency_LHV, eps) * 100;
        gain_rows(end + 1, :) = { ...
            case_name, topology_label, topology_id, best_theta, ...
            best_theta_dyn.hydrogen_t, milp_dyn.hydrogen_t, hydrogen_gain_percent, ...
            best_theta_dyn.efficiency_LHV, milp_dyn.efficiency_LHV, efficiency_gain_percent, ...
            best_theta_active, mean(sum(milp.Pmodule_MW > 1e-9, 2)), ...
            best_theta_curtailment_MWh, milp_curtailment_MWh, ...
            mean(eq_theta.equivalent_theta), std(eq_theta.equivalent_theta), ...
            prctile(eq_theta.equivalent_theta, 10), median(eq_theta.equivalent_theta), ...
            prctile(eq_theta.equivalent_theta, 90), mean(eq_theta.theta_fit_rmse_MW) ...
            }; %#ok<SAGROW>

        case_key = char(matlab.lang.makeValidName(sprintf('%s_%s', case_name, topology_label)));
        process_mat = fullfile(process_dir, sprintf('%s_milp_dynamic_process.mat', case_key));
        daily_compare = table((1:n_days)', ...
            milp_used_energy_day, milp_hydrogen_day, milp_eta_day_mean, milp_curtailment_day_MWh, milp_active_day_mean, ...
            best_theta_used_energy_day, best_theta_hydrogen_day, best_theta_eta_day_mean, best_theta_curtailment_day_MWh, best_theta_active_day_mean, ...
            'VariableNames', {'day_id', ...
            'milp_used_energy_day_MWh', 'milp_hydrogen_day_t', 'milp_eta_day_mean', 'milp_curtailment_day_MWh', 'milp_active_modules_day_mean', ...
            'theta_used_energy_day_MWh', 'theta_hydrogen_day_t', 'theta_eta_day_mean', 'theta_curtailment_day_MWh', 'theta_active_modules_day_mean'});
        daily_compare_csv = fullfile(process_dir, sprintf('%s_dynamic_daily_compare.csv', case_key));
        writetable(daily_compare, daily_compare_csv);
        save(process_mat, 'case_name', 'topology_label', 'topology_id', 'P_available', 'P_capped', ...
            'milp', 'milp_dyn', 'eq_theta', 'best_theta', 'best_theta_schedule', 'best_theta_dyn', ...
            'theta_process', 'daily_compare', '-v7.3');
    end
end

summary = cell2table(summary_rows, 'VariableNames', { ...
    'case_name', 'topology_label', 'topology_id', 'strategy', 'theta', ...
    'n_modules', 'plant_rating_MW', ...
    'mean_load_raw', 'mean_load_capped', ...
    'available_energy_MWh', 'capped_available_energy_MWh', 'used_energy_MWh', ...
    'hydrogen_t', 'efficiency_LHV_used_energy_basis', ...
    'curtailment_MWh', 'mean_active_modules', ...
    'equivalent_theta_mean', 'equivalent_theta_fit_rmse_MW_mean', ...
    'loading_gini_mean' ...
    });

theta_detail = cell2table(theta_rows, 'VariableNames', { ...
    'case_name', 'topology_label', 'topology_id', 'theta', ...
    'n_modules', 'plant_rating_MW', ...
    'mean_load_raw', 'mean_load_capped', 'used_energy_MWh', ...
    'hydrogen_t', 'efficiency_LHV_used_energy_basis', ...
    'curtailment_MWh', 'mean_active_modules' ...
    });

gain = cell2table(gain_rows, 'VariableNames', { ...
    'case_name', 'topology_label', 'topology_id', 'best_theta_dynamic', ...
    'hydrogen_theta_t', 'hydrogen_milp_t', 'hydrogen_gain_percent', ...
    'efficiency_theta', 'efficiency_milp', 'efficiency_gain_percent', ...
    'active_modules_theta', 'active_modules_milp', ...
    'curtailment_theta_MWh', 'curtailment_milp_MWh', ...
    'equivalent_theta_mean', 'equivalent_theta_std', ...
    'equivalent_theta_p10', 'equivalent_theta_median', ...
    'equivalent_theta_p90', 'equivalent_theta_fit_rmse_MW_mean' ...
    });

theta_summary = cell2table(theta_summary_rows, 'VariableNames', { ...
    'case_name', 'topology_label', 'topology_id', ...
    'equivalent_theta_mean', 'equivalent_theta_std', ...
    'equivalent_theta_min', 'equivalent_theta_p10', ...
    'equivalent_theta_median', 'equivalent_theta_p90', ...
    'equivalent_theta_max', 'theta_fit_rmse_MW_mean', ...
    'active_modules_mean', 'loading_gini_mean' ...
    });

theta_daily = cell2table(theta_daily_rows, 'VariableNames', { ...
    'case_name', 'topology_label', 'topology_id', 'day_id', ...
    'equivalent_theta_daily_mean', 'equivalent_theta_daily_std', ...
    'theta_fit_rmse_MW_daily_mean', 'active_modules_daily_mean', ...
    'loading_gini_daily_mean', 'P_available_MW_daily_mean' ...
    });

summary = numeric_table_columns(summary);
theta_detail = numeric_table_columns(theta_detail);
gain = numeric_table_columns(gain);
theta_summary = numeric_table_columns(theta_summary);
theta_daily = numeric_table_columns(theta_daily);
profile_summary = cell2table(profile_rows, 'VariableNames', { ...
    'case_name', 'n_modules', 'plant_rating_MW', ...
    'mean_load_raw', 'mean_load_capped', ...
    'available_energy_MWh', 'capped_available_energy_MWh', ...
    'min_power_MW', 'max_power_MW', 'n_days' ...
    });
profile_summary = numeric_table_columns(profile_summary);

out_xlsx = fullfile(cfg.output_dir, sprintf('plant_milp_dynamic_closed_loop%s.xlsx', file_suffix));
out_summary_csv = fullfile(cfg.output_dir, sprintf('plant_milp_dynamic_closed_loop%s_summary.csv', file_suffix));
out_theta_csv = fullfile(cfg.output_dir, sprintf('plant_theta_dynamic_closed_loop%s_detail.csv', file_suffix));
out_gain_csv = fullfile(cfg.output_dir, sprintf('plant_milp_dynamic_closed_loop%s_gain.csv', file_suffix));
out_eq_summary_csv = fullfile(cfg.output_dir, sprintf('plant_milp_equivalent_theta%s_summary.csv', file_suffix));
out_eq_daily_csv = fullfile(cfg.output_dir, sprintf('plant_milp_equivalent_theta%s_daily.csv', file_suffix));
out_eq_mat = fullfile(cfg.output_dir, sprintf('plant_milp_equivalent_theta%s_timeseries.mat', file_suffix));
out_profile_csv = fullfile(process_dir, 'plant_milp_case_profile_summary.csv');

writetable(summary, out_summary_csv);
writetable(theta_detail, out_theta_csv);
writetable(gain, out_gain_csv);
writetable(theta_summary, out_eq_summary_csv);
writetable(theta_daily, out_eq_daily_csv);
writetable(profile_summary, out_profile_csv);
save(out_eq_mat, 'theta_series', '-v7.3');

writetable(summary, out_xlsx, 'Sheet', 'summary');
writetable(theta_detail, out_xlsx, 'Sheet', 'theta_grid');
writetable(gain, out_xlsx, 'Sheet', 'gain');
writetable(theta_summary, out_xlsx, 'Sheet', 'equiv_theta_summary');
writetable(theta_daily, out_xlsx, 'Sheet', 'equiv_theta_daily');

fig_data_xlsx = fullfile(cfg.figure_dir, 'Fig4_R1_MILP_dynamic_closed_loop_data.xlsx');
writetable(summary, fig_data_xlsx, 'Sheet', 'summary');
writetable(gain, fig_data_xlsx, 'Sheet', 'gain');
writetable(theta_summary, fig_data_xlsx, 'Sheet', 'equiv_theta_summary');
writetable(theta_daily, fig_data_xlsx, 'Sheet', 'equiv_theta_daily');

plot_equivalent_theta_preview(theta_daily, gain, cfg);

fprintf('Plant MILP dynamic closed loop complete:\n');
fprintf('  %s\n', out_xlsx);
fprintf('  %s\n', out_gain_csv);
fprintf('  %s\n', out_eq_daily_csv);
disp(gain);

function add_equivalent_theta_summary(eq_theta, case_name, topology_label, topology_id)
theta_summary_rows(end + 1, :) = { ...
    case_name, topology_label, topology_id, ...
    mean(eq_theta.equivalent_theta), std(eq_theta.equivalent_theta), ...
    min(eq_theta.equivalent_theta), prctile(eq_theta.equivalent_theta, 10), ...
    median(eq_theta.equivalent_theta), prctile(eq_theta.equivalent_theta, 90), ...
    max(eq_theta.equivalent_theta), mean(eq_theta.theta_fit_rmse_MW), ...
    mean(eq_theta.active_modules), mean(eq_theta.loading_gini) ...
    }; %#ok<SAGROW>
end

function add_equivalent_theta_daily(eq_theta, case_name, topology_label, topology_id)
days = unique(eq_theta.day_id);
for dd = 1:numel(days)
    idx = eq_theta.day_id == days(dd);
    theta_daily_rows(end + 1, :) = { ...
        case_name, topology_label, topology_id, days(dd), ...
        mean(eq_theta.equivalent_theta(idx)), std(eq_theta.equivalent_theta(idx)), ...
        mean(eq_theta.theta_fit_rmse_MW(idx)), mean(eq_theta.active_modules(idx)), ...
        mean(eq_theta.loading_gini(idx)), mean(eq_theta.P_available_MW(idx)) ...
        }; %#ok<SAGROW>
end
end

function T = numeric_table_columns(T)
for j = 1:width(T)
    if iscell(T.(j)) && all(cellfun(@(x) isnumeric(x) && isscalar(x), T.(j)))
        T.(j) = cell2mat(T.(j));
    end
end
end

end
