function cfg = degradation_model_config()
%DEGRADATION_MODEL_CONFIG Configuration for the rebuilt six-unit degradation workflow.

src_dir = fileparts(mfilename('fullpath'));
model_root = fileparts(src_dir);
degradation_root = fileparts(model_root);
workflow_root = fileparts(degradation_root);

cfg = struct();
cfg.src_dir = src_dir;
cfg.model_root = model_root;
cfg.degradation_root = degradation_root;
cfg.workflow_root = workflow_root;

cfg.raw_data_dir = fullfile(model_root, 'raw_data');
cfg.current_version_dir = fullfile(model_root, 'current_version');
cfg.step1_dir = fullfile(cfg.current_version_dir, 'step1_clean_target');
cfg.step2_dir = fullfile(cfg.current_version_dir, 'step2_model_benchmark');
cfg.step3_dir = fullfile(cfg.current_version_dir, 'step3_diagnostics');

cfg.raw_timeseries_csv = fullfile(cfg.raw_data_dir, 'raw_timeseries_current_version_6units.csv');

cfg.units = {'PV1', 'PV2', 'PV3', 'PV4', 'PV5', 'WIND1'};
cfg.unit_cell_count = struct( ...
    'PV1', 382, ...
    'PV2', 382, ...
    'PV3', 382, ...
    'PV4', 382, ...
    'PV5', 382, ...
    'WIND1', 182);

cfg.baseline_days = 40;
cfg.baseline_min_current_frac = 0.10;
cfg.baseline_state_threshold = 0.95;
cfg.target_min_current_frac = 0.85;
cfg.daily_smooth_window_days = 7;
cfg.daily_rate_half_window_days = 3;
cfg.train_ratio = 0.80;
cfg.extrapolation_horizon_days = 365;
cfg.extrapolation_pattern_days = 30;
cfg.random_seed = 42;

cfg.baseline_candidate_names = { ...
    'Linear IT', ...
    'Quadratic I + Linear T', ...
    'Quadratic IT + Interaction'};

cfg.feature_columns = { ...
    'elapsed_day', ...
    'sqrt_elapsed_day', ...
    'log1p_elapsed_day', ...
    'daily_eflh_h', ...
    'mean_power_frac_all', ...
    'mean_power_frac_on', ...
    'p90_power_frac_on', ...
    'high_load_hours', ...
    'ramp_abs_mean_frac', ...
    'ramp_abs_max_frac', ...
    'rated_hours', ...
    'transition_hours', ...
    'stop_hours', ...
    'start_count', ...
    'stop_count', ...
    'cum_daily_eflh_h', ...
    'cum_high_load_hours', ...
    'cum_start_count', ...
    'cum_stop_count'};

cfg.target_column = 'daily_deg_rate_cell_mV';

cfg.model_families = { ...
    'Linear Regression', ...
    'Regression Tree', ...
    'Bagged Trees', ...
    'Gradient Boosting', ...
    'Gaussian Process', ...
    'Support Vector Regression'};

cfg.step1_baseline_comparison_csv = fullfile(cfg.step1_dir, 'voltage_baseline_model_comparison.csv');
cfg.step1_baseline_selected_csv = fullfile(cfg.step1_dir, 'voltage_baseline_selected_models.csv');
cfg.step1_hourly_equivalent_csv = fullfile(cfg.step1_dir, 'hourly_equivalent_voltage.csv');
cfg.step1_daily_target_csv = fullfile(cfg.step1_dir, 'daily_clean_degradation_targets.csv');
cfg.step1_summary_txt = fullfile(cfg.step1_dir, 'step1_summary.txt');

cfg.step2_training_table_csv = fullfile(cfg.step2_dir, 'daily_training_table.csv');
cfg.step2_model_comparison_csv = fullfile(cfg.step2_dir, 'daily_rate_model_comparison.csv');
cfg.step2_best_model_metrics_csv = fullfile(cfg.step2_dir, 'best_model_metrics.csv');
cfg.step2_daily_predictions_csv = fullfile(cfg.step2_dir, 'daily_rate_predictions.csv');
cfg.step2_best_model_mat = fullfile(cfg.step2_dir, 'best_model_refit.mat');
cfg.step2_summary_txt = fullfile(cfg.step2_dir, 'step2_summary.txt');

cfg.step3_daily_rate_png = fullfile(cfg.step3_dir, 'daily_rate_target_vs_prediction.png');
cfg.step3_cumulative_png = fullfile(cfg.step3_dir, 'cumulative_degradation_curves_6units.png');
cfg.step3_curve_csv = fullfile(cfg.step3_dir, 'cumulative_curve_table.csv');
cfg.step3_summary_txt = fullfile(cfg.step3_dir, 'step3_summary.txt');

output_dirs = {cfg.current_version_dir, cfg.step1_dir, cfg.step2_dir, cfg.step3_dir};
for i = 1:numel(output_dirs)
    if ~exist(output_dirs{i}, 'dir')
        mkdir(output_dirs{i});
    end
end
end
